//
//  LoginConfigurator.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/6/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension LoginViewController: LoginPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension LoginInteractor: LoginViewControllerOutput
{
}

extension LoginPresenter: LoginInteractorOutput
{
}

class LoginConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = LoginConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: LoginViewController)
  {
    let router = LoginRouter()
    router.viewController = viewController
    
    let presenter = LoginPresenter()
    presenter.output = viewController
    
    let interactor = LoginInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
