//
//  LoginModels.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/6/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Login {
  struct FetchUser {
    struct Request {
        var id:String
    }
    struct Response {
        var user:PersonModel
    }
    struct ViewModel {
        struct DisplayedPerson {
            var codelec: String
            var id: String
            var junta: String
            var sexo: String
            var apellido1: String
            var apellido2: String
            var nombre: String
            var fechacaduc: String
        }
        var displayedPerson:DisplayedPerson
    }
    struct Error {
        var title: String
        var message: String
    }
  }
}
