//
//  LoginViewController.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/6/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginViewControllerInput {
    func displayPerson(_ viewModel: Login.FetchUser.ViewModel)
}

protocol LoginViewControllerOutput {
    func fetchUser(request: Login.FetchUser.Request)
    var person:PersonModel? {get}
}

class LoginViewController: UIViewController, LoginViewControllerInput, UITextFieldDelegate {
    var output: LoginViewControllerOutput!
    var router: LoginRouter!
    @IBOutlet var idTextFields: [UITextField]!
    @IBOutlet weak var id1TextField: UITextField!
    @IBOutlet weak var id2TextField: UITextField!
    @IBOutlet weak var id3TextField: UITextField!
    
    // MARK: - Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        LoginConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - Display logic
    
    func displayPerson(_ viewModel: Login.FetchUser.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
        print("Full Name is: \(viewModel.displayedPerson.nombre) \(viewModel.displayedPerson.apellido1) \(viewModel.displayedPerson.apellido2)")
        OperationQueue.main.addOperation {
                 self.performSegue(withIdentifier: "SucessLoginSegueId", sender: self)
        }
    }
    
    // MARK: - TextFieldDelegate
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        if let index = idTextFields.index(of: textField) {
            if index < idTextFields.count - 1 {
                let nextTextField = idTextFields[index + 1]
                nextTextField.becomeFirstResponder()
            }
        }
        return true
    }
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        if (string.rangeOfCharacter(from: CharacterSet.letters) != nil) {
            return false
        }
        guard let text = textField.text else { return true }
        let newLength = text.characters.count + string.characters.count - range.length
        
        if textField.tag == 0 {
            return newLength <= 1 // Bool
        } else {
            return newLength <= 4 // Bool
        }
    }
    
    // MARK: - Event Handling
    @IBAction func loginButtonPressed(_ sender: AnyObject) {

        
        let idText = "\(id1TextField.text!)\(id2TextField.text!)\(id3TextField.text!)"
        print("La cedula a consultar es: \(idText)")
        let request = Login.FetchUser.Request(id:idText)
        output.fetchUser(request: request)
    }
}
