//
//  LoginPresenter.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/6/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LoginPresenterInput{

    func presentError(_ error: PersonStoreError)
  func presentPerson(_ response: Login.FetchUser.Response)
}

protocol LoginPresenterOutput: class {
    func displayPerson(_ viewModel: Login.FetchUser.ViewModel)
    func displayError(_ error: Login.FetchUser.Error)
}

class LoginPresenter: LoginPresenterInput
{
  weak var output: LoginPresenterOutput!
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = DateFormatter.Style.none
        return dateFormatter
    }()
  
  // MARK: - Presentation logic
  
  func presentPerson(_ response: Login.FetchUser.Response) {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    let date = dateFormatter.string(from: response.user.fechacaduc! as Date)
    
    let displayedPerson = Login.FetchUser.ViewModel.DisplayedPerson(codelec: "\(response.user.codelec)", id: "\(response.user.id)", junta: "\(response.user.junta)", sexo: "\(response.user.sexo)", apellido1: response.user.apellido1!, apellido2: response.user.apellido2!, nombre: response.user.nombre!, fechacaduc: date)
    
    let viewModel = Login.FetchUser.ViewModel(displayedPerson:displayedPerson)
    
    output.displayPerson(viewModel)
  }
    
    func presentError(_ error: PersonStoreError) {
        let err = Login.FetchUser.Error(title: "Error al Iniciar Sesión", message: error.localizedDescription )
        output.displayError(err)
    }

}
