//
//  MeetUsInteractor.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/7/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MeetUsInteractorInput
{
  func doSomething(request: MeetUs.Something.Request)
}

protocol MeetUsInteractorOutput
{
  func presentSomething(response: MeetUs.Something.Response)
}

class MeetUsInteractor: MeetUsInteractorInput
{
  var output: MeetUsInteractorOutput!
  var worker: MeetUsWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: MeetUs.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = MeetUsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = MeetUs.Something.Response()
    output.presentSomething(response: response)
  }
}
