//
//  MeetUsPresenter.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/7/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MeetUsPresenterInput
{
  func presentSomething(response: MeetUs.Something.Response)
}

protocol MeetUsPresenterOutput: class
{
  func displaySomething(viewModel: MeetUs.Something.ViewModel)
}

class MeetUsPresenter: MeetUsPresenterInput
{
  weak var output: MeetUsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: MeetUs.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = MeetUs.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
