//
//  ProfileConfigurator.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/7/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ProfileViewController: ProfilePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ProfileInteractor: ProfileViewControllerOutput
{
}

extension ProfilePresenter: ProfileInteractorOutput
{
}

class ProfileConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ProfileConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ProfileViewController)
  {
    let router = ProfileRouter()
    router.viewController = viewController
    
    let presenter = ProfilePresenter()
    presenter.output = viewController
    
    let interactor = ProfileInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
