//
//  ProfilePresenter.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/7/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProfilePresenterInput
{
  func presentSomething(response: Profile.Something.Response)
}

protocol ProfilePresenterOutput: class
{
  func displaySomething(viewModel: Profile.Something.ViewModel)
}

class ProfilePresenter: ProfilePresenterInput
{
  weak var output: ProfilePresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: Profile.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = Profile.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
