//
//  ProfileInteractor.swift
//  Figueres2018
//
//  Created by Javier Jara on 12/7/16.
//  Copyright (c) 2016 Data Center Consultores. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ProfileInteractorInput
{
  func doSomething(request: Profile.Something.Request)
}

protocol ProfileInteractorOutput
{
  func presentSomething(response: Profile.Something.Response)
}

class ProfileInteractor: ProfileInteractorInput
{
  var output: ProfileInteractorOutput!
  var worker: ProfileWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Profile.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ProfileWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Profile.Something.Response()
    output.presentSomething(response: response)
  }
}
